name: mipripity
description: A property listing mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  google_fonts: ^5.1.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  flutter_plugin_android_lifecycle: ^2.0.28
  # Added dependencies for image/video handling
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  video_player: ^2.9.5
  cached_network_image: ^3.3.0
  # Added for form handling
  form_field_validator: ^1.1.0
  # Added for UI improvements
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  # Added for location picking
  geocoding: ^2.1.1
  # Added for WhatsApp integration
  whatsapp_unilink: ^2.0.2
  firebase_auth: ^5.6.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mipripity.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
